### ISSUE TITLE
Could i get CVE numbers for reporting the bugs

### ISSUE THREAD

**Issue by thereksfour** [athre0z/wasm#4]
I fuzzed this library and got some crash. Could i get cve numbers for reporting the bugs. crash like this:

```
    for cur_sec, cur_sec_data in mod_iter:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wasm/decode.py", line 45, in decode_module
    sec_len, sec_data, _ = sec.from_raw(None, module_wnd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wasm/types.py", line 302, in from_raw
    data_len, val, data_type = cur_field.from_raw(data, raw[offs:])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wasm/types.py", line 188, in from_raw
    return self.choice_field_map[choice].from_raw(ctx, raw)
KeyError: 90
```

**Comment by athre0z** [comment]
Could you explain how this is a security issue? Right now, the lib lacks graceful reporting for errors encountered due to incorrect input files, but I don't see how this would be a security issue worth a CVE.

**Comment by athre0z** [comment]
Don't get me wrong, I do see that this is an issue and plan on addressing it. It's been on my TODO for a while now. I just don't think it qualifies as a security issue.

**Comment by thereksfour** [comment]
I am sorry for my words. I just think it might be a DOS. When people uses this lib in his website, it will occur.

**Comment by athre0z** [comment]
Even if the lib were to be used in a website, it wouldn’t cause DoS. It’s a regular, catchable Python exception. The preferred mean of gracefully reporting failure in Python. It is in the responsibility of anyone using the lib in, for example, a website, to catch it. It’s just pretty ugly that right now it just forwards the KeyError instead of re-throwing it into something more fitting, e.g. “BadFormatError”, and I do plan on addressing that. Despite that, throwing an exception for malformed input files is the only sane choice.
